# Initial setup
FROM openjdk:8-jdk-alpine AS base

ENV BC_VERSION 1.0-SNAPSHOT
ENV CHAIN_ID 30
ENV IP_MASK 20.20.200
ENV VAULT_NAME password-server
ENV VAULT_LISTEN_PORT 20565
ENV VAULT_SERVERS 20.20.200.42:20563

RUN mkdir /setlnet

COPY pychain-cmdtools/build/libs/pychain-cmdtools-all-${BC_VERSION}.jar .

RUN java \
    -Dio.setl.bc.store.bos.useSparseFiles=true \
    -cp pychain-cmdtools-all-${BC_VERSION}.jar io.setl.bc.pychain.cmdline.InitialUtil \
    --root=/setlnet \
    --singleserver=yes \
    --chaincount=1 \
    --chainidbegin=30 \
    --nodecount=3 \
    --docker.mask=${IP_MASK} \
    --setl.vault.name=${VAULT_NAME} \
    --setl.vault.servers=${VAULT_SERVERS} \
    --bos \
    --scale=14

RUN java \
    -Dio.setl.bc.store.bos.useSparseFiles=true \
    -cp pychain-cmdtools-all-${BC_VERSION}.jar io.setl.bc.pychain.cmdline.InitialUtil \
    --root=/setlnet \
    --singleserver=yes \
    --chaincount=1 \
    --chainidbegin=50 \
    --nodecount=5 \
    --docker.mask=${IP_MASK} \
    --setl.vault.name=${VAULT_NAME} \
    --setl.vault.servers=${VAULT_SERVERS} \
    --bos \
    --scale=14

RUN java \
    -Dio.setl.bc.store.bos.useSparseFiles=true \
    -cp pychain-cmdtools-all-${BC_VERSION}.jar io.setl.bc.pychain.cmdline.InitialUtil \
    --root=/setlnet \
    --singleserver=yes \
    --chaincount=1 \
    --chainidbegin=70 \
    --nodecount=7 \
    --docker.mask=${IP_MASK} \
    --setl.vault.name=${VAULT_NAME} \
    --setl.vault.servers=${VAULT_SERVERS} \
    --bos \
    --scale=14

RUN java \
    -Dio.setl.bc.store.bos.useSparseFiles=true \
    -cp pychain-cmdtools-all-${BC_VERSION}.jar io.setl.bc.pychain.cmdline.InitialUtil \
    --root=/setlnet \
    --singleserver=yes \
    --chaincount=1 \
    --chainidbegin=90 \
    --nodecount=9 \
    --docker.mask=${IP_MASK} \
    --setl.vault.name=${VAULT_NAME} \
    --setl.vault.servers=${VAULT_SERVERS} \
    --bos \
    --scale=14

# Wallet Node
FROM base AS w-node

WORKDIR /wallet_node

COPY pychain-node-wallet/build/libs/pychain-node-wallet-${BC_VERSION}.jar .
COPY native/libed25519-donna.so .
COPY --from=base /setlnet /setlnet

ENV NODE_ID 3
ENV JVM_DEBUG_PORT 9003
ENV WS_PATH db

CMD java \
    -Dio.setl.bc.store.bos.useSparseFiles=true \
    -Djava.library.path=/wallet_node \
    -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=${JVM_DEBUG_PORT} \
    -jar pychain-node-wallet-${BC_VERSION}.jar \
    --spring.config.location=/setlnet/${CHAIN_ID}/setl${NODE_ID}.properties \
    --transport=netty \
    --db-store.type=sqlite \
    --management.endpoint.health.enabled=true \
    --health.user=jenson \
    --health.password=onepathMalta \
    --setl.vault.name=${VAULT_NAME} \
    --setl.vault.listen=${VAULT_LISTEN_PORT} \
    --setl.vault.servers=${VAULT_SERVERS} \
    --ws.path=${WS_PATH}

# Validation Node
FROM base AS v-node

WORKDIR /validation_node

COPY pychain-node-validation-dev/build/libs/pychain-node-validation-dev-${BC_VERSION}.jar .
COPY native/libed25519-donna.so .
COPY --from=base /setlnet /setlnet

ENV NODE_ID 0
ENV JVM_DEBUG_PORT 9000

CMD java \
    -Dio.setl.bc.store.bos.useSparseFiles=true \
    -Djava.library.path=/validation_node \
    -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=${JVM_DEBUG_PORT} \
    -jar pychain-node-validation-dev-${BC_VERSION}.jar \
    --spring.config.location=/setlnet/${CHAIN_ID}/setl${NODE_ID}.properties \
    --transport=netty \
    --db-store.type=sqlite \
    --nostart=false \
    --demowallet=wallet-0.dat \
    --management.endpoint.health.enabled=true \
    --health.user=jenson \
    --health.password=onepathMalta \
    --setl.vault.name=${VAULT_NAME} \
    --setl.vault.listen=${VAULT_LISTEN_PORT} \
    --setl.vault.servers=${VAULT_SERVERS}
