CREATE DATABASE IF NOT EXISTS `blockchain0` DEFAULT CHARACTER SET utf8;
CREATE DATABASE IF NOT EXISTS `blockchain1` DEFAULT CHARACTER SET utf8;
CREATE DATABASE IF NOT EXISTS `blockchain2` DEFAULT CHARACTER SET utf8;
CREATE DATABASE IF NOT EXISTS `blockchain3` DEFAULT CHARACTER SET utf8;
CREATE DATABASE IF NOT EXISTS `blockchain4` DEFAULT CHARACTER SET utf8;
